datasketch/weighted_minhash.py

By default, random generator produces doubles and that is not affordable with millions of dimensions.

Convert weighted minhash's state to float32

---

datasketch/lsh.py

The same byte result but much faster and actually always the same length.
The old approach is wrong: e.g. len("%.4x"% 741282) is 5, not 4.

Dramatically speedup and fix LSH's _H()

---

benchmark/minhash_benchmark.py
datasketch/minhash.py
test/minhash_test.py

I am not sure if your MinHash implementation is supposed to give the  same results on different versions of Python. It currently does not do so. I added the test vectors for the results I get on python 2.7. Unfortunately Python 3.5 gives different results. See: https://travis-ci.org/ekzhu/datasketch/builds/214433266

Test MinHash against fixed result vector

---

.travis.yml
datasketch/lsh.py
datasketch/storage.py
docsrc/lsh.rst
setup.py
test/lsh_test.py
test/lshensemble_test.py

We have been using datasketch extensively in data-driven applications (primarily the `MinHashLSH` class). The existing implementation requires all data to be stored in memory, which is a severe limitation for very large datasets. We add support for a Redis backend. Default behavior remains in-memory storage.
- Redis backend for `MinHashLSH`
- Insertion session for bulk insertion (reduces network calls when inserting with a Redis backend)
- Functionality to view LSH bucket sizes (useful for diagnosis/debugging)
- Accompanying docs and tests
For examples, see the additions to the documentation.

Redis backend for datasketch LSH

---

datasketch/storage.py

Noticed a bug with the Redis implementation of `getmany` for set storage.

Fix a bug with RedisSetStorage.getmany

---

datasketch/experimental/aio/storage.py
docsrc/lsh.rst

Hi @ekzhu,
I'd like to add an extension to the `AsyncMongoStorage` class -- ability to pass custom params to the constructor of the underlying `pymongo.MongoClient`.

allow passing custom parameters to the constructor of AsyncIOMotorClient

---

datasketch/b_bit_minhash.py
datasketch/hyperloglog.py
datasketch/minhash.py
datasketch/weighted_minhash.py

If I compare datasketch-provided objects against any other type, an error occurs:
```
from datasketch import HyperLogLog
HyperLogLog(p=4) == None
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-130aff532e0c> in <module>()
----> 1 HyperLogLog(p=4) == None
/.../eggs/datasketch-1.4.1-py2.7.egg/datasketch/hyperloglog.py in __eq__(self, other)
206             bool: True if both have the same internal state.
207         '''
--> 208         if self.p != other.p:
209             return False
210         if self.m != other.m:
AttributeError: 'NoneType' object has no attribute 'p'
```
This is troublesome in a few situations where code I don't control chooses to compare e.g. …

Allow equality comparisons against non-datasketch values

---

datasketch/hyperloglog.py

HyperLogLog performs linear counting when the estimate is below a certain threshold. The decision to perform linear counting is based on the estimate, rather than the real count (which is obviously unavailable).
This can lead to cases where the real count is above the threshold but the estimate is below it, triggering linear counting where it is not necessary. The opposite scenario can also occur.
These scenarios lead to a deviation from the accuracy guarantee provided by the authors Flajolet et al. on page 15 of their [paper](http://algo.inria.fr/flajolet/Publications/FlFuGaMe07.pdf) in cases where the real count / estimate is close to the threshold. We used statistical testing to verify that this deviation from accuracy mostly occurs when the estimate is within 15% of the threshold. …

Add warning for when estimate is close to error correction threshold

---

datasketch/lsh.py

* if the number of buckets was larger than 256 it failed when the buckets names were composed
* fixed by using `struct.pack` instead of `bytes`
fixes https://github.com/ekzhu/datasketch/issues/102

fix bug where lsh failed with ValueError

---

datasketch/lsh.py

I've added the option to pass in a hash function to MinHashLSH. As the cut-off threshold is increased the hash ranges get larger, resulting in larger bucket keys. The hash function can be used to cap the size of these keys, reducing memory footprint. It only makes sense to do this when the hash ranges are larger than 1.
With some naive testing, this change resulted in as much as 90% smaller memory footprint at high thresholds. [Check out my benchmark gist](https://gist.github.com/Sinusoidal36/290041ba98234cf4aaa6d1c0ceed42c0)
What do you think of this approach? Using a 64-bit hash function I think it is quite unlikely this would increase false positives due to collisions. It may even be reasonable to hash the buckets to fewer bits if false positives aren't a concern.

Reduce MinHashLSH memory footprint by hashing buckets

---

datasketch/experimental/aio/storage.py

Fixes #146, can be verified by querying the db during tests. The index on 'key' is now being created in each bucket and the 'keys' collection too.
```
> show collections
lsh_nbzqpzsztag_bucket_0
lsh_nbzqpzsztag_bucket_1
lsh_nbzqpzsztag_bucket_2
lsh_nbzqpzsztag_bucket_3
lsh_nbzqpzsztag_bucket_4
lsh_nbzqpzsztag_keys
> db.lsh_nbzqpzsztag_bucket_0.getIndexes()
[
{
"v" : 2,
"key" : {
"_id" : 1
},
"name" : "_id_"
},
{
"v" : 2,
"key" : {
"key" : 1
},
"name" : "key_1"
}
]
> db.lsh_nbzqpzsztag_keys.getIndexes()
[
{
"v" : 2,
"key" : {
"_id" : 1
},
"name" : "_id_"
},
{
"v" : 2,
"key" : {
"key" : 1
},
"name" : "key_1"
}
]
> 
```

Fixes #146; MinhashLSH creates mongo index key.

---

datasketch/storage.py

Some redis protocol compatible storage (e.g., kvrocks) do not support `MULTI` and `EXEC` command, but they may support pipeline execution. So here provide `transaction` option to the caller to choose if enable transaction.
Currently the redis client will raise a exception when use `lsh.insertion_session`:
```
Traceback (most recent call last):
File "large_similar_codes_query_perf.py", line 97, in <module>
session.insert(f"m{i}", m)
File "/Users/qintianhuan/.pyenv/versions/ma/lib/python3.7/site-packages/datasketch-1.5.3-py3.7.egg/datasketch/lsh.py", line 335, in insert
File "/Users/qintianhuan/.pyenv/versions/ma/lib/python3.7/site-packages/datasketch-1.5.3-py3.7.egg/datasketch/lsh.py", line 185, in _insert
File "/Users/qintianhuan/.pyenv/versions/ma/lib/python3.7/site-packages/datasketch-1. …
```

Add `redis_buffer` configuration.

---

datasketch/minhash.py

Hi!
The MinHash implementation uses np.float for internal computations.
With Numpy 1.20 is np.float alias deprecated and generates the following
warning:
```
minhash.py:179: DeprecationWarning: `np.float` is a deprecated alias for
the builtin `float`. To silence this warning, use `float` by itself.
Doing this will not modify any behavior and is safe. If you specifically
wanted the numpy scalar type, use `np.float64` here.
```
I am not sure whether there is a specific need for NumPy scalar type but
I assumed that not. If I am wrong, I can replace the float with np.float64.

minhash: Get rid of deprecation warning

---

datasketch/lsh.py
datasketch/storage.py
test/test_lsh.py
test/test_lsh_cassandra.py

Inserting a new `MinHash` into a `MinHashLSH` with the cassandra backend gets a great performance boost from using an insertion session together with `shared_buffer` activated because then, the insert queries into all hash tables are done concurrently. Unfortunately, I did not find an equivalently performant way for querying a `MinHash`.
This PR adds a way to also make use of a shared buffer with the cassandra backend when querying data. The procedure is split into two parts: `add_to_query_buffer` and `collect_query_buffer`: Calling them in sequence should be equivalent to calling `query` but alot faster:
```python
lsh.add_to_query_buffer(min_hash)
buffered = lsh.collect_query_buffer()
direct = lsh.query(min_hash)
assert set(buffered) == set(direct)
```
Splitting the function into two …

Add query buffer

---

datasketch/storage.py

- omitting keyspace when connecting to Cassandra, this will set the default Cassandra keyspace
- when running `get_session` if the current keyspace is not the same as the configuration we create the keyspace if needed and set it as current.

Unable to create multiple lsh indices each one in its own keyspace - issue #171

---

datasketch/storage.py
test/test_lsh.py

https://github.com/ekzhu/datasketch/blob/master/datasketch/lsh.py#L118
In lsh.py when we are iterating over values of b and b reaches 95 the packed value of 95 contains an underscore
```python
In [7]: for i in range(100):
...:     print(i, struct.pack('>H', i))
...: 
0 b'\x00\x00'
1 b'\x00\x01'
2 b'\x00\x02'
3 b'\x00\x03'
4 b'\x00\x04'
5 b'\x00\x05'
6 b'\x00\x06'
7 b'\x00\x07'
8 b'\x00\x08'
9 b'\x00\t'
10 b'\x00\n'
11 b'\x00\x0b'
12 b'\x00\x0c'
13 b'\x00\r'
14 b'\x00\x0e'
15 b'\x00\x0f'
16 b'\x00\x10'
17 b'\x00\x11'
18 b'\x00\x12'
19 b'\x00\x13'
20 b'\x00\x14'
.....
.....
95 b'\x00_' # This is an issue for unpacking after split
96 b'\x00`'
97 b'\x00a'
98 b'\x00b'
99 b'\x00c'
```
this completely breaks this naming here due to split and you get unpacking error.
```python
In [32]: name = …
```

Fix name construction for all values of b

---

datasketch/lsh.py

Fixes incorrect docstring and should hopefully eliminate some usage confusion

Update MinHashLSH.query docstring detailing proximal nature of results

---

datasketch/lsh.py
datasketch/minhash.py
test/test_lsh.py

This arguably makes the code easier to read, and reduces one transpose `.T` operation.
the `ndmin=2` is required for the transpose to be valid.

simplify reshapes

---

datasketch/lshforest.py
test/test_lshforest.py

Adds the ability to retrieve a `MinHash` from the `MinHashLSHForest` object, which is useful in workflows where we wish to manually threshold the results of a top-k query from the LSHForest.
```
lsh = MinHashLSHForest(...)
mh = lsh.get_minhash_from_key(mykey)
```
Please let me know if I should change any naming/formatting, I tried my best to keep in step with what was already present.
@ekzhu 
closes #233

Retrieve MinHash from LSHForest

---

.github/workflows/test.yml
datasketch/lsh.py
docs/lsh.rst
examples/lsh_examples.py
test/test_lsh.py

Merging two MinHashLSH of the same length (num_perm).

-Issue: #205: Merging (Identically Specified) MinHashLSH objects

---

benchmark/sketches/b_bit_minhash_benchmark.py

Update the benchmark for `bBitMinHash`.

Update bBitMinHash Benchmark
